/* ============================================================================
 * OMANDISTAN — game.js
 * Game state, input handling, the Omand approval flow, kindness events, the
 * simulation loop, and all UI wiring. Loaded last.
 * ==========================================================================*/
(function () {
  "use strict";
  const C = window.CONFIG;
  const E = window.Economy;
  const R = window.Render;

  // ---- Game state ---------------------------------------------------------
  const state = {
    treasury: C.START.treasury,
    loveTokens: C.START.loveTokens,
    population: C.START.population,
    happiness: C.START.happiness,
    buildings: [],
    grid: [],                       // grid[row][col] -> building ref or null
    month: 0,
    lastPriceIndex: 0,
    policies: { publicHealth: false, taxRate: C.ECON.taxRate },
    stats: null,
  };
  for (let r = 0; r < C.MAP.rows; r++) state.grid.push(new Array(C.MAP.cols).fill(null));

  let selectedType = null;          // currently chosen build tool
  let hover = null;                 // {cx,cy}
  let speedIndex = 0;               // index into CONFIG.SPEEDS
  let tickTimer = null;
  let pendingLoveFraction = 0;      // accumulate fractional love tokens

  const MONTHS = ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

  // ---- DOM refs -----------------------------------------------------------
  const $ = (id) => document.getElementById(id);
  let canvas;

  function log(msg, kind) {
    const el = $("log");
    const line = document.createElement("div");
    line.className = "logline" + (kind ? " " + kind : "");
    line.textContent = msg;
    el.prepend(line);
    while (el.children.length > 40) el.removeChild(el.lastChild);
  }

  // =========================================================================
  // BUILD / OMAND APPROVAL
  // =========================================================================
  function isWater(cx, cy) {
    return cx <= 0 || cy <= 0 || cx >= C.MAP.cols - 1 || cy >= C.MAP.rows - 1;
  }
  function touchesWater(cx, cy) {
    return isWater(cx - 1, cy) || isWater(cx + 1, cy) || isWater(cx, cy - 1) || isWater(cx, cy + 1);
  }

  function tryPlace(cx, cy) {
    if (!selectedType) return;
    if (cx === C.CASTLE.cx && cy === C.CASTLE.cy) {
      log("That's the royal castle — the Omands live there! 🏰", "warn"); return;
    }
    if (isWater(cx, cy)) {
      log("That's the sea — you can't build on open water.", "warn");
      return;
    }
    if (state.grid[cy][cx]) { log("That tile is already occupied.", "warn"); return; }
    const def = C.BUILDINGS[selectedType];
    if (def.requiresWater && !touchesWater(cx, cy)) {
      log(`A ${def.name} must be built on the coast — place it next to the water. 🌊`, "warn");
      return;
    }
    if (state.treasury < def.cost) {
      log(`Not enough money for a ${def.name} ($${def.cost} needed).`, "warn");
      return;
    }
    if (def.love > 0 && state.loveTokens < def.love) {
      log(`Mr. & Mrs. Omand require ${def.love} Spreading Love token to approve this. Do acts of kindness to earn more! 💞`, "warn");
      flashOmand("We need to see more kindness first, dear builder.");
      return;
    }
    // Pay costs (Omand approval consumes the love token).
    state.treasury -= def.cost;
    if (def.love > 0) {
      state.loveTokens -= def.love;
      flashOmand(`Approved! ${def.icon} (−${def.love} 💞)`);
    }
    const b = { type: selectedType, cx, cy };
    state.buildings.push(b);
    state.grid[cy][cx] = b;
    log(`Built ${def.name} ${def.icon} at (${cx},${cy}).`, "good");
    // Bootstrap: first home invites a few founding settlers.
    if (selectedType === "house" && state.population === 0) {
      state.population = 6;
      log("6 founding settlers move into Omandistan! 🎉", "good");
    }
    refreshStats();
  }

  function bulldoze(cx, cy) {
    const b = state.grid[cy] && state.grid[cy][cx];
    if (!b) return;
    state.grid[cy][cx] = null;
    state.buildings = state.buildings.filter((x) => x !== b);
    log(`Removed ${C.BUILDINGS[b.type].name}.`, "");
    refreshStats();
  }

  // A small flash from the royal couple.
  let omandTimer = null;
  function flashOmand(text) {
    const el = $("omandFlash");
    el.querySelector(".omand-text").textContent = text;
    el.classList.add("show");
    clearTimeout(omandTimer);
    omandTimer = setTimeout(() => el.classList.remove("show"), 2600);
  }

  // =========================================================================
  // SIMULATION TICK
  // =========================================================================
  function doTick() {
    state.month += C.START.monthsPerTick;
    const s = E.tick(state);
    state.stats = s;

    // apply results
    state.treasury += s.treasury.net;
    state.population = Math.max(0, state.population + s.popChange);
    state.happiness = s.happiness;
    state.lastPriceIndex = s.priceIndex;

    // love tokens generated by kindness centers
    pendingLoveFraction += s.lovePerTick;
    if (pendingLoveFraction >= 1) {
      const whole = Math.floor(pendingLoveFraction);
      state.loveTokens += whole;
      pendingLoveFraction -= whole;
    }

    // narrate notable changes
    if (s.popChange > 0) log(`+${s.popChange} immigrants arrived (happiness ${Math.round(s.happiness)}). 🧳`, "good");
    else if (s.popChange < 0) log(`${s.popChange} citizens emigrated — conditions are tough. 📉`, "warn");
    if (state.treasury < 0) log("⚠️ Treasury is in the red! Cut upkeep or raise output.", "warn");

    // occasionally trigger an act-of-kindness event
    maybeEvent();

    refreshStats();
  }

  // =========================================================================
  // EVENTS (acts of kindness / helping struggling civilizations)
  // =========================================================================
  let eventOpen = false;
  function maybeEvent() {
    if (eventOpen) return;
    if (state.population < 8) return;
    if (Math.random() < 0.18) openEvent(C.EVENTS[Math.floor(Math.random() * C.EVENTS.length)]);
  }

  function openEvent(ev) {
    eventOpen = true;
    setSpeed(0); // pause for the decision
    const m = $("modal");
    m.innerHTML = `
      <div class="card">
        <h2>💞 ${ev.title}</h2>
        <p>${ev.text}</p>
        <p class="cost">Cost: $${ev.costMoney} &nbsp;·&nbsp; Reward: +${ev.reward} 💞 Love &nbsp;·&nbsp; +${ev.happiness} happiness</p>
        <div class="row">
          <button id="evYes" class="btn primary">${ev.yes}</button>
          <button id="evNo" class="btn">${ev.no}</button>
        </div>
      </div>`;
    m.classList.add("show");
    $("evYes").onclick = () => {
      if (state.treasury < ev.costMoney) { log("Not enough money to help right now.", "warn"); }
      else {
        state.treasury -= ev.costMoney;
        state.loveTokens += ev.reward;
        state.happiness = Math.min(100, state.happiness + ev.happiness);
        log(`Act of kindness! +${ev.reward} 💞 Love tokens, +${ev.happiness} happiness.`, "good");
        flashOmand("Such kindness! Omandistan grows more beloved. 💛");
      }
      closeEvent();
    };
    $("evNo").onclick = () => { log("You declined to help.", ""); closeEvent(); };
  }
  function closeEvent() {
    $("modal").classList.remove("show");
    eventOpen = false;
    setSpeed(1);
  }

  // =========================================================================
  // STATS / HUD
  // =========================================================================
  function refreshStats() {
    if (!state.stats) state.stats = E.tick(state);
    const s = state.stats;
    const pct = (x) => Math.round(x * 100) + "%";
    const money = (x) => "$" + Math.round(x).toLocaleString();

    setChip("c-treasury", money(state.treasury));
    setChip("c-love", Math.floor(state.loveTokens) + " 💞");
    setChip("c-pop", Math.round(state.population).toLocaleString());
    setChip("c-happy", Math.round(state.happiness) + " / 100");
    setChip("c-gdp", money(s.gdp));
    setChip("c-prod", "×" + s.productivity.toFixed(2));
    setChip("c-unemp", pct(s.labor.unemployment));
    setChip("c-date", `${MONTHS[(state.month) % 12]} Yr ${1 + Math.floor(state.month / 12)}`);

    // detail panel
    const reg = s.health.regulated;
    $("detail").innerHTML = `
      <div class="dgroup"><h4>🌾 Food — Perfect Competition</h4>
        <div>Price: <b>$${s.food.price.toFixed(2)}</b> ${trend(s.food.price, C.ECON.food.refPrice)}</div>
        <div>Supply ${Math.round(s.food.supply)} / Demand ${Math.round(s.food.demand)} · Access ${pct(s.food.access)}</div>
        <div>Farm profit: <b class="${s.food.farmProfit>=0?'pos':'neg'}">${money(s.food.farmProfit)}</b> <span class="hint">(→ 0 in long run)</span></div>
      </div>
      <div class="dgroup"><h4>🏥 Healthcare — ${reg ? "Public Option" : "Monopoly"}</h4>
        <div>Price: <b>$${s.health.price.toFixed(2)}</b> ${reg ? '<span class="pos">regulated</span>' : '<span class="neg">markup</span>'}</div>
        <div>Served ${Math.round(s.health.served)} / Demand ${Math.round(s.health.demand)} · Access ${pct(s.health.access)}</div>
        ${reg ? `<div>Subsidy cost: ${money(s.health.subsidy)}/mo</div>`
              : `<div>People priced out (DWL): <b class="neg">${Math.round(s.health.dwl)}</b></div>`}
      </div>
      <div class="dgroup"><h4>🛒 Goods — Elastic Luxury</h4>
        <div>Price: <b>$${s.goods.price.toFixed(2)}</b> · Sold ${Math.round(s.goods.sold)}/${Math.round(s.goods.supply)}</div>
      </div>
      <div class="dgroup"><h4>🎓 Human Capital — PPC</h4>
        <div>Productivity: <b class="${s.productivity>1.01?'pos':''}">×${s.productivity.toFixed(2)}</b> <span class="hint">(educated workers → outward PPC)</span></div>
        <div>Education points ${Math.round(s.humanCapital)} · coverage ${pct(s.hcUtil)}</div>
      </div>
      <div class="dgroup"><h4>🚢 Global Trade</h4>
        ${s.trade.capacity > 0
          ? `<div>Capacity ${Math.round(s.trade.capacity)}/mo · Exports +${money(s.trade.exportIncome)} · Imports −${money(s.trade.importCost)}</div>
             <div>Tourism +${money(s.trade.tourismIncome)}/mo · Net trade <b class="${s.trade.net>=0?'pos':'neg'}">${money(s.trade.net)}</b></div>`
          : `<div class="hint">Build a Seaport 🚢 or Airport ✈️ to open global trade.</div>`}
      </div>
      <div class="dgroup"><h4>📊 Macro</h4>
        <div>Inflation: <b class="${Math.abs(s.inflation)<0.03?'pos':'neg'}">${(s.inflation*100).toFixed(1)}%</b> · Tax: ${money(s.treasury.tax)}/mo</div>
        <div>Housing ${Math.round(s.housing)} (free ${Math.round(s.housingFree)}) · Jobs ${s.labor.jobs} / Labor ${s.labor.force}</div>
      </div>`;

    // happiness meter color
    const meter = $("happyfill");
    meter.style.width = Math.round(state.happiness) + "%";
    meter.style.background = state.happiness > 66 ? "#4e9d5b" : state.happiness > 40 ? "#d9a441" : "#cc5b5b";
  }

  function trend(v, ref) {
    if (v > ref * 1.05) return '<span class="neg">▲</span>';
    if (v < ref * 0.95) return '<span class="pos">▼</span>';
    return "";
  }
  function setChip(id, val) { const el = $(id); if (el) el.textContent = val; }

  // =========================================================================
  // TOOLBAR / POLICIES
  // =========================================================================
  function buildToolbar() {
    const bar = $("toolbar");
    for (const key of C.BUILD_ORDER) {
      const def = C.BUILDINGS[key];
      const btn = document.createElement("button");
      btn.className = "tool";
      btn.innerHTML = `<span class="ticon">${def.icon}</span><span class="tname">${def.name}</span>
        <span class="tcost">$${def.cost}${def.love ? " · 1💞" : ""}</span>`;
      btn.title = def.desc;
      btn.onclick = () => selectTool(key, btn);
      bar.appendChild(btn);
    }
    // bulldoze tool
    const bd = document.createElement("button");
    bd.className = "tool bulldoze";
    bd.innerHTML = `<span class="ticon">⛏️</span><span class="tname">Bulldoze</span><span class="tcost">free</span>`;
    bd.onclick = () => selectTool("__bulldoze", bd);
    bar.appendChild(bd);
  }

  function selectTool(key, btn) {
    document.querySelectorAll(".tool").forEach((b) => b.classList.remove("active"));
    if (selectedType === key || (key === "__bulldoze" && selectedType === "__bulldoze")) {
      selectedType = null; return;        // toggle off
    }
    selectedType = key;
    btn.classList.add("active");
    const def = C.BUILDINGS[key];
    if (def) log(`${def.name}: ${def.desc}`, "info");
  }

  function togglePublicHealth() {
    state.policies.publicHealth = !state.policies.publicHealth;
    const on = state.policies.publicHealth;
    $("btnHealth").textContent = on ? "🏥 Healthcare: Public Option (ON)" : "🏥 Healthcare: Monopoly";
    $("btnHealth").classList.toggle("on", on);
    flashOmand(on ? "We decree affordable care for all! 🩺" : "The market shall set the price.");
    log(on ? "Omand decree: healthcare priced near cost — access rises, treasury subsidises it."
           : "Healthcare returns to a private monopoly: higher price, fewer served.", "info");
    refreshStats();
  }

  // =========================================================================
  // SPEED CONTROL
  // =========================================================================
  function setSpeed(i) {
    speedIndex = i;
    document.querySelectorAll(".speedbtn").forEach((b, idx) => b.classList.toggle("active", idx === i));
    if (tickTimer) { clearInterval(tickTimer); tickTimer = null; }
    const ms = C.SPEEDS[i].ms;
    if (ms > 0) tickTimer = setInterval(doTick, ms);
  }

  // =========================================================================
  // INPUT
  // =========================================================================
  function setupInput() {
    let dragging = false, dragMoved = false, lastX = 0, lastY = 0;

    canvas.addEventListener("mousedown", (e) => {
      dragging = true; dragMoved = false; lastX = e.clientX; lastY = e.clientY;
    });
    window.addEventListener("mouseup", (e) => {
      if (dragging && !dragMoved) {
        const rect = canvas.getBoundingClientRect();
        const t = R.screenToTile(e.clientX - rect.left, e.clientY - rect.top);
        if (selectedType === "__bulldoze") bulldoze(t.cx, t.cy);
        else if (selectedType) tryPlace(t.cx, t.cy);
      }
      dragging = false;
    });
    canvas.addEventListener("mousemove", (e) => {
      const rect = canvas.getBoundingClientRect();
      hover = R.screenToTile(e.clientX - rect.left, e.clientY - rect.top);
      if (dragging) {
        const dx = e.clientX - lastX, dy = e.clientY - lastY;
        if (Math.abs(dx) + Math.abs(dy) > 4) dragMoved = true;
        R.pan(dx, dy); lastX = e.clientX; lastY = e.clientY;
      }
    });
    canvas.addEventListener("mouseleave", () => { hover = null; });

    // keyboard: arrows pan, space toggles play/pause
    window.addEventListener("keydown", (e) => {
      const step = 40;
      if (e.key === "ArrowLeft") R.pan(step, 0);
      else if (e.key === "ArrowRight") R.pan(-step, 0);
      else if (e.key === "ArrowUp") R.pan(0, step);
      else if (e.key === "ArrowDown") R.pan(0, -step);
      else if (e.key === " ") { e.preventDefault(); setSpeed(speedIndex === 0 ? 1 : 0); }
      else if (e.key === "Escape") { selectedType = null; document.querySelectorAll(".tool").forEach((b)=>b.classList.remove("active")); }
    });
  }

  // =========================================================================
  // TUTORIAL (step-through, shown on first open; reopen via Help)
  // =========================================================================
  let tutStep = 0;
  function openTutorial(step) {
    tutStep = step || 0;
    setSpeed(0);
    renderTutorial();
    $("welcome").classList.add("show");
  }
  function renderTutorial() {
    const steps = C.TUTORIAL;
    const s = steps[tutStep];
    const last = tutStep === steps.length - 1;
    const dots = steps.map((_, i) => `<span class="dot ${i === tutStep ? "on" : ""}"></span>`).join("");
    $("welcome").innerHTML = `
      <div class="card tutcard">
        <div class="omand-faces" style="font-size:34px;text-align:center">👑👸</div>
        <h2>${s.title}</h2>
        <p>${s.body}</p>
        <div class="tutdots">${dots}</div>
        <div class="row">
          ${tutStep > 0 ? '<button id="tutBack" class="btn">◀ Back</button>' : '<span></span>'}
          <button id="tutNext" class="btn primary">${last ? "Start building 🚜" : "Next ▶"}</button>
        </div>
        ${!last ? '<button id="tutSkip" class="tutskip">Skip tutorial</button>' : ''}
      </div>`;
    if ($("tutBack")) $("tutBack").onclick = () => { tutStep--; renderTutorial(); };
    $("tutNext").onclick = () => {
      if (last) closeTutorial(); else { tutStep++; renderTutorial(); }
    };
    if ($("tutSkip")) $("tutSkip").onclick = closeTutorial;
  }
  function closeTutorial() {
    $("welcome").classList.remove("show");
    setSpeed(1);
    log("Tip: build Housing 🏠 first, then a Farm 🌾 and a Market 🛒. Press Play ▶. 👑", "info");
  }

  // =========================================================================
  // RENDER LOOP
  // =========================================================================
  function renderLoop() {
    R.frame(state, hover, selectedType === "__bulldoze" ? null : selectedType);
    requestAnimationFrame(renderLoop);
  }

  // =========================================================================
  // BOOT
  // =========================================================================
  function boot() {
    canvas = $("game");
    R.init(canvas);
    buildToolbar();
    setupInput();

    // speed buttons
    const sc = $("speed");
    C.SPEEDS.forEach((sp, i) => {
      const b = document.createElement("button");
      b.className = "speedbtn"; b.textContent = sp.label;
      b.onclick = () => setSpeed(i);
      sc.appendChild(b);
    });

    $("btnHealth").onclick = togglePublicHealth;
    $("btnHelp").onclick = () => openTutorial(0);

    refreshStats();
    renderLoop();
    openTutorial(0);
  }

  window.addEventListener("DOMContentLoaded", boot);
})();
